edited

diff --git a/.github/workflows/custom-pr-comment.yml b/.github/workflows/custom-pr-comment.yml
--- a/.github/workflows/custom-pr-comment.yml
+++ b/.github/workflows/custom-pr-comment.yml
@@ -1,30 +1,59 @@
 name: Custom Scanner PMD
+
 on:
-#  pull_request:
-#    types: [opened, reopened, synchronize, edited]
   workflow_dispatch:
+
 jobs:
-  pmd-code-scan:
+  get-changed-files:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 11
-        uses: actions/setup-java@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Fetch PR files
+        id: fetch_pr_files
+        uses: actions/github-script@v6
         with:
-          java-version: '11'
-          distribution: 'temurin'
-      - name: Run PMD
-        id: pmd
-        uses: pmd/pmd-github-action@v2
-        with:
-          rulesets: 'config/scanner/pmd_config.xml'
-          sourcePath: 'src'
-          analyzeModifiedFilesOnly: true
-          uploadSarifReport: false
-          createGitHubAnnotations: true
-      - name: Fail build if there are violations
-        if: steps.pmd.outputs.violations != 0
-        run: exit 1
+          script: |
+            const pr_number = context.payload.pull_request.number;
+            const { data: files } = await github.pulls.listFiles({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              pull_number: pr_number,
+            });
+            return files.map(file => file.filename);
+
+      - name: Output changed file names
+        run: |
+          echo "Changed files: ${{ steps.fetch_pr_files.outputs.result }}"
+#on:
+##  pull_request:
+##    types: [opened, reopened, synchronize, edited]
+#  workflow_dispatch:
+#jobs:
+#  pmd-code-scan:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: '11'
+#          distribution: 'temurin'
+#      - name: Run PMD
+#        id: pmd
+#        uses: pmd/pmd-github-action@v2
+#        with:
+#          rulesets: 'config/scanner/pmd_config.xml'
+#          sourcePath: 'src'
+#          analyzeModifiedFilesOnly: true
+#          uploadSarifReport: false
+#          createGitHubAnnotations: true
+#      - name: Fail build if there are violations
+#        if: steps.pmd.outputs.violations != 0
+#        run: exit 1
+#
+#        -----------------------------------------------------------------
 #      - name: Upload SARIF file
 #        uses: github/codeql-action/upload-sarif@v3
 #        with:
